#!/bin/bash

if test $# -eq 0; then
 echo "Empty arguments!"; exit 11
fi

ASSERT_OPTION="$1"

case "$ASSERT_OPTION" in
 -eq)
  . ex/util/args/require $# 3
  EXPECTED="$2"
  ACTUAL="$3"
  . ex/util/require $EXPECTED $ACTUAL
  if test "${!EXPECTED}" != "${!ACTUAL}"; then
   echo "Actual is \"${!ACTUAL}\", but expected is \"${!EXPECTED}\"!"; exit 23
  fi;;
 -f)
  . ex/util/args/require $# 2
  FILE_PATH="$2"
  . ex/util/require FILE_PATH
  if [ ! -f "$FILE_PATH" ]; then
   echo "File $FILE_PATH does not exist!"; exit 21
  fi;;
 -d)
  . ex/util/args/require $# 2
  DIR_PATH="$2"
  . ex/util/require DIR_PATH
  if [ ! -d "$DIR_PATH" ]; then
   echo "Dir $DIR_PATH does not exist!"; exit 21
  fi;;
 *) echo "Assert | Option \"$ASSERT_OPTION\" is not supported!"; exit 91;;
esac
