#!/bin/bash

OUTPUT=/tmp/jqx.o

. ex/util/args/require $# 3 > $OUTPUT

JQX_OPTION="$1"
JSON_FILE="$2"
JSON_QUERY="$3"

. ex/util/require JQX_OPTION JSON_FILE JSON_QUERY > $OUTPUT
. ex/util/assert -f $JSON_FILE > $OUTPUT

case "$JQX_OPTION" in
 -sfs) JSON_OPTION="select((.!=null)and(type==\"string\")and(.!=\"\"))";;
 -sb) JSON_OPTION="select((.!=null)and(type==\"boolean\"))"
  RESULT="$(jq -Mcer "${JSON_QUERY}|${JSON_OPTION}" $JSON_FILE 2> $OUTPUT)"; CODE=$?
  if test $CODE -eq 0; then
   if test "$RESULT" == "true"; then
    echo "$RESULT"; exit 0
   fi
   . ex/util/throw 121 "Unexpected boolean value \"$RESULT\"!" > $OUTPUT
  elif test $CODE -eq 1; then
   if test "$RESULT" == "false"; then
    echo "$RESULT"; exit 0
   fi
   . ex/util/throw 122 "Unexpected boolean value \"$RESULT\"!" > $OUTPUT
  fi
  echo "Json parse boolean error!"; exit 123;;
 -si) JSON_OPTION="select((.!=null)and(type==\"number\"))";;
 *) . ex/util/throw 13 "JQ | Option \"$JQX_OPTION\" is not supported!" > $OUTPUT;;
esac

RESULT="$(jq -Mcer "${JSON_QUERY}|${JSON_OPTION}" $JSON_FILE 2> $OUTPUT)"; CODE=$?
if test $CODE -ne 0; then
 . ex/util/throw 14 "Json parse by option \"$JQX_OPTION\" error!" > $OUTPUT
fi

echo "$RESULT"

exit 0
