#!/bin/bash

if test $# -ne 2; then
 echo "Unexpected argument number!"; exit 91
fi

ACTUAL_NUMBER=$1
EXPECTED_NUMBER=$2

if [[ "$ACTUAL_NUMBER" =~ [1-9][0-9]* || "$ACTUAL_NUMBER" == "0" ]]; then
 if [[ "$EXPECTED_NUMBER" =~ [1-9][0-9]* || "$EXPECTED_NUMBER" == "0" ]]; then
  /bin/true
 else
  echo "Expected value is not a number ($EXPECTED_NUMBER)!"; exit 93
 fi
else
 echo "Actual value is not a number ($ACTUAL_NUMBER)!"; exit 92
fi

if test $ACTUAL_NUMBER -ne $EXPECTED_NUMBER; then
 echo "Script needs for $EXPECTED_NUMBER argument, but actual is $ACTUAL_NUMBER!"; exit 11
fi
