#!/bin/bash

OUTPUT=/tmp/jqm.o

[ $# -lt 2 ] && . ex/util/throw 11 "Script needs more arguments!" > $OUTPUT

VARIABLE="$1"

. ex/util/require VARIABLE > $OUTPUT

CODE=0
for ((i=2; i<=$#; i++)); do
 JSON_QUERY="${!i}"
 . ex/util/require JSON_QUERY > $OUTPUT
 tmp="$(echo "${!VARIABLE}" | jq -Mc "$JSON_QUERY")"; CODE=$?
 if test $CODE -ne 0; then
  . ex/util/throw $((100 + $i)) "Json merge [$(($i - 1))/$(($# - 1))] \"$VARIABLE\" error!" > $OUTPUT
 fi
 printf -v "$VARIABLE" '%s' "$tmp"
done
