#!/bin/bash

OUTPUT=/tmp/jqx.o

. ex/util/args/require $# 3 > $OUTPUT

JQX_OPTION="$1"
JSON_FILE="$2"
JSON_QUERY="$3"

. ex/util/require JQX_OPTION JSON_FILE JSON_QUERY > $OUTPUT
. ex/util/assert -f $JSON_FILE > $OUTPUT

JQ_CODE=0

case "$JQX_OPTION" in
 -sfs) JSON_OPTION="select((.!=null)and(type==\"string\")and(.!=\"\"))";;
 -sb) JSON_OPTION="select((.!=null)and(type==\"boolean\"))"
  JQ_RESULT="$(jq -Mcer "${JSON_QUERY}|${JSON_OPTION}" $JSON_FILE 2> $OUTPUT)"; JQ_CODE=$?
  if test $JQ_CODE -eq 0; then
   if test "$JQ_RESULT" == "true"; then
    echo "$JQ_RESULT"; exit 0
   fi
   . ex/util/throw 121 "Unexpected boolean value \"$JQ_RESULT\"!" > $OUTPUT
  elif test $JQ_CODE -eq 1; then
   if test "$JQ_RESULT" == "false"; then
    echo "$JQ_RESULT"; exit 0
   fi
   . ex/util/throw 122 "Unexpected boolean value \"$JQ_RESULT\"!" > $OUTPUT
  fi
  echo "Json parse boolean error!"; exit 123;;
 -si) JSON_OPTION="select((.!=null)and(type==\"number\"))";;
 *) . ex/util/throw 13 "JQ | Option \"$JQX_OPTION\" is not supported!" > $OUTPUT;;
esac

JQ_RESULT="$(jq -Mcer "${JSON_QUERY}|${JSON_OPTION}" $JSON_FILE 2> $OUTPUT)"; JQ_CODE=$?
[ $JQ_CODE -ne 0 ] && . ex/util/throw 21 "Json parse $JSON_FILE by option \"$JQX_OPTION\" error!" > $OUTPUT

echo "$JQ_RESULT"
