#!/bin/bash

. ex/util/args/require $# 2

THROW_CODE=$1
THROW_MESSAGE="$2"

. ex/util/require THROW_CODE THROW_MESSAGE

if [[ "$THROW_CODE" =~ [1-9][0-9]* ]]; then
 if test $THROW_CODE -eq 0; then
  echo "Unknown error code!"; exit 13
 fi
 echo "$THROW_MESSAGE"; exit $THROW_CODE
fi

echo "Code format error \"$THROW_CODE\"!"; exit 14
